sudo: required
services:
  - docker

before_install:
  - docker build -t jstalle/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jstalle/react-test npm test

after_success:
  - docker build -t jstalle/multi-client ./client
  - docker build -t jstalle/multi-nginx ./nginx
  - docker build -t jstalle/multi-server ./server
  - docker build -t jstalle/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jstalle/multi-client
  - docker push jstalle/multi-nginx
  - docker push jstalle/multi-server
  - docker push jstalle/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-central-1-635003165228
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
